### ISSUE TITLE
Issue with installing chromaR

### ISSUE THREAD

**Issue by ghost** [detsutut/chroma#6]
Hi! Thank you for your contribution. 
When following the code towardsdatascience (fun article!),
> install_github("detsutut/chroma", subdir="chromaR")

R fails to install due to error in dyn.load(file, DLLpath = DLLpath, ...) : unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/imager/libs/imager....., reason being image not found and lazy loading failed for package 'chromaR'

**Comment by detsutut** [comment]
Hi and apologies for the delay.
Library load errors are usually due to PATH environment variable issues. Since I wasn't able to replicate your problem, I can only suggest to:
1) check your PATH variables 
2) try to reinstall the package 
3) try to reinstall R and R studio
